#!/usr/bin/env python3
"""Generate every agent integration file from one source of truth.

Run this after changing ``api/agent_registry.py`` or ``api/agent_docs.py``:

    python scripts/generate_agent_docs.py

It writes the instruction files that coding agents pick up automatically
(``AGENTS.md``, ``CLAUDE.md``, ``GEMINI.md``, ``.cursor/rules/`` …), the MCP
server registrations, the per-agent reference docs under ``docs/agents/``, and
the served skill documents.  Use ``--check`` in CI to fail when the committed
files are stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:  # Python 3.11+
    import tomllib
except ImportError:  # pragma: no cover - 3.10 fallback
    tomllib = None

try:
    import yaml
except ImportError:  # pragma: no cover - optional dev dependency
    yaml = None

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from api.agent_docs import (  # noqa: E402
    PROJECT_NAME,
    build_manifest,
    canonical_body,
    render_agent_doc,
    render_skill,
)
from api.agent_registry import AGENTS, AGENTS_BY_ID  # noqa: E402

BASE_URL = "http://localhost:8000"

# Comment syntax differs per file format; using the wrong one produces a file
# the target tool cannot parse (an HTML comment is not valid TOML or YAML).
MARKUP_HEADER = (
    "<!-- Generated by scripts/generate_agent_docs.py — do not edit by hand. -->\n"
)
HASH_HEADER = (
    "# Generated by scripts/generate_agent_docs.py — do not edit by hand.\n"
)

# Kept as an alias so the markdown producers read naturally.
GENERATED_HEADER = MARKUP_HEADER

# File extensions whose formats support `#` comments.
HASH_COMMENT_SUFFIXES = (".toml", ".yml", ".yaml", ".cfg", ".ini", ".conf")


def header_for(path: str) -> str:
    """The comment line appropriate for ``path``, or '' when none is safe."""
    if path.endswith(HASH_COMMENT_SUFFIXES):
        return HASH_HEADER
    return MARKUP_HEADER

# ── Shared payloads ─────────────────────────────────────────────────────────


def mcp_stdio_config() -> dict:
    """The MCP server block every config format shares."""
    return {
        "command": "python",
        "args": ["mcp_server.py"],
        "env": {"AUTO_GET_BASE_URL": BASE_URL},
    }


def mcp_servers_json() -> dict:
    return {"mcpServers": {"auto-get-py": mcp_stdio_config()}}


def _capability_summary() -> str:
    return canonical_body("/api/agent", BASE_URL)


def _quick_reference(prefix: str = "/api/agent") -> str:
    return f"""\
## Quick reference

| Task | Call |
|---|---|
| Is it running? | `curl {BASE_URL}/api/health` |
| What exists on a page? | `POST {prefix}/quick` with `{{"url": "…", "crawl_depth": 2}}` |
| Download it all | `POST {prefix}/scrape` with `{{"url": "…", "wait": true}}` |
| Render a JS page and download | `POST {prefix}/direct` with `{{"url": "…"}}` |
| One exact file | `POST {prefix}/fetch` with `{{"url": "…"}}` |
| Progress | `GET {prefix}/status/{{id}}` |
| Final files | `GET {prefix}/results/{{id}}` |
| Stop it | `POST {prefix}/cancel/{{id}}` |

Prefer the MCP tools (`scrape`, `quick_scrape`, `fetch_file`, `task_status`,
`task_results`, `cancel_task`, `list_files`) when your client supports MCP —
they wrap the same endpoints with better descriptions.
"""


# ── Root-level instruction files ────────────────────────────────────────────


def build_agents_md() -> str:
    rows = "\n".join(
        f"| {agent.name} | `{agent.primary_prefix}` | "
        f"{', '.join(f'`{p}`' for p in agent.config_files) or '—'} |"
        for agent in AGENTS
    )
    return f"""{GENERATED_HEADER}# AGENTS.md — {PROJECT_NAME}

This repository contains **{PROJECT_NAME}**, a local media scraper. Agents
working in this repository can use it to download images, video, audio,
documents and archives from any web page or site.

## Start the service

```bash
pip install -r requirements.txt
python app.py                 # http://localhost:8000
playwright install chromium   # optional, only for JavaScript-heavy sites
```

## Use it

{_quick_reference()}

{_capability_summary()}

## Agent integrations available in this repository

| Agent | URL alias | Config files |
|---|---|---|
{rows}

Every alias serves the identical API. The full registry is available at
`GET /api/agent/agents` and the machine-readable manifest at
`GET /api/agent/manifest`.

## MCP

`mcp_server.py` exposes the scraper as MCP tools over stdio:

```bash
python mcp_server.py
```

Register it with:

```json
{json.dumps(mcp_servers_json(), indent=2)}
```

## Repository conventions

- Python 3.10+, FastAPI + aiohttp + aiosqlite. No synchronous I/O in the
  request path.
- `scraper/engine.py` orchestrates crawling and transfer; `scraper/extractor.py`
  owns URL discovery; `scraper/downloader.py` owns transfer, including HLS/DASH
  merging. Keep new discovery strategies in the extractor, not the engine.
- Database access goes through `db/queries.py`. Never write SQL elsewhere.
- Schema changes go in `db/schema.py` **and** `_MIGRATIONS`, so existing
  databases upgrade in place.
- Every agent-facing file is generated: edit `api/agent_registry.py` or
  `api/agent_docs.py`, then run `python scripts/generate_agent_docs.py`.
- Tests: `python -m pytest tests/ -q`.
"""


def build_claude_md() -> str:
    return f"""{GENERATED_HEADER}# CLAUDE.md — {PROJECT_NAME}

{_quick_reference("/api/claude")}

{_capability_summary()}

## Tooling in this repository

- **Skill**: `.claude/skills/auto-get-py/SKILL.md` — dropped in, ready to load.
- **MCP**: `.mcp.json` registers `mcp_server.py`, giving the `scrape`,
  `quick_scrape`, `fetch_file`, `task_status`, `task_results`, `cancel_task` and
  `list_files` tools.

## Working on the codebase

- `python -m pytest tests/ -q` must stay green.
- The end-to-end crawler fixture is `tests/local_site.py`; use it instead of
  hitting the real internet in tests.
- Agent integration files are generated. Change `api/agent_registry.py` or
  `api/agent_docs.py`, then:
  `python scripts/generate_agent_docs.py`.
"""


def build_gemini_md() -> str:
    return f"""{GENERATED_HEADER}# GEMINI.md — {PROJECT_NAME}

{_quick_reference("/api/gemini")}

{_capability_summary()}
"""


def build_rules_markdown(agent_id: str, prefix: str) -> str:
    agent = AGENTS_BY_ID[agent_id]
    return f"""{GENERATED_HEADER}# {PROJECT_NAME} — {agent.name} rules

When the user asks to scrape, crawl, or batch-download media from a website,
use the local {PROJECT_NAME} service instead of writing a bespoke script.

{_quick_reference(prefix)}

{_capability_summary()}

## {agent.name} notes

{agent.notes or "—"}
"""


def build_cursor_rule() -> str:
    return f"""---
description: Download media from web pages with the local Auto-Get-PY scraper
globs:
alwaysApply: false
---
{GENERATED_HEADER}
# Auto-Get-PY — media scraping

Use the local scraper service at {BASE_URL} whenever the user asks to scrape,
crawl, or batch-download images/video/audio/documents from a URL.

{_quick_reference("/api/cursor")}

**Workflow:** health check → `POST /quick` to preview → show the user what was
found → `POST /scrape` to download → poll `/status/{id}` → report `/results/{id}`.

Prefer MCP tools (`scrape`, `quick_scrape`, `fetch_file`) if the
`auto-get-py` server from `.cursor/mcp.json` is connected.
"""


def build_opencode_json() -> str:
    return json.dumps({
        "$schema": "https://opencode.ai/config.json",
        "mcp": {
            "auto-get-py": {
                "type": "local",
                "command": ["python", "mcp_server.py"],
                "enabled": True,
                "environment": {"AUTO_GET_BASE_URL": BASE_URL},
            }
        },
    }, indent=2) + "\n"


def build_opencode_agent() -> str:
    return f"""---
description: Downloads media from web pages using the local Auto-Get-PY scraper
mode: subagent
tools:
  bash: true
  read: true
  write: false
---
{GENERATED_HEADER}
# scraper subagent

You download media from web pages. Always use the local {PROJECT_NAME}
service — never write a new scraper from scratch.

{_quick_reference("/api/opencode")}

## Procedure

1. `curl {BASE_URL}/api/health` — if it fails, tell the user to run
   `python app.py` and stop.
2. `POST /quick` with `crawl_depth: 2` to see what is available.
3. Report the count and a few example URLs.
4. On confirmation, `POST /scrape`. Poll `/status/{{id}}` and report progress.
5. Finish with `/results/{{id}}`: how many files, where they are, what failed.

Do not claim success for files listed under `failed_files`.
"""


def build_dsh_mcp() -> str:
    return json.dumps({
        "mcpServers": {"auto-get-py": {**mcp_stdio_config(),
                                       "description": "Web media scraper"}},
    }, indent=2) + "\n"


def build_codex_config() -> str:
    # A TOML file, so `#` comments — and deliberately no absolute path, which
    # would be wrong on every other machine (and differ in CI).
    return f"""{HASH_HEADER}# Copy the block below into ~/.codex/config.toml
# (or merge it into an existing .codex/config.toml).
#
# Run Codex from the repository root so `mcp_server.py` resolves. If you launch
# it from somewhere else, uncomment the next line and use an absolute path:
# cwd = "/absolute/path/to/Auto-Get-PY"

[mcp_servers.auto_get_py]
command = "python"
args = ["mcp_server.py"]

[mcp_servers.auto_get_py.env]
AUTO_GET_BASE_URL = "{BASE_URL}"
"""


def build_codex_readme() -> str:
    return f"""{GENERATED_HEADER}# Codex integration

Codex reads `AGENTS.md` from the repository root automatically — that file
already documents the scraper API.

For first-class tool access, merge `.codex/config.toml` into
`~/.codex/config.toml`:

```toml
[mcp_servers.auto_get_py]
command = "python"
args = ["mcp_server.py"]

[mcp_servers.auto_get_py.env]
AUTO_GET_BASE_URL = "{BASE_URL}"
```

Then `codex` gains the tools `scrape`, `quick_scrape`, `fetch_file`,
`task_status`, `task_results`, `cancel_task`, `list_files`.

## Custom prompt

`.codex/prompts/scrape.md` defines a reusable prompt:

```
codex "…"    # then reference the prompt, or paste its body
```
"""


def build_codex_prompt() -> str:
    return f"""{GENERATED_HEADER}# Scrape a URL for media

Fetch the media from: **$ARGUMENTS**

Steps:

1. Confirm the service is up: `curl {BASE_URL}/api/health`
2. Preview with `POST {BASE_URL}/api/codex/quick`:
   ```bash
   curl -s {BASE_URL}/api/codex/quick -H 'Content-Type: application/json' \\
     -d '{{"url": "$ARGUMENTS", "crawl_depth": 2}}'
   ```
3. Report how many assets were found.
4. Download with `POST {BASE_URL}/api/codex/scrape`:
   ```bash
   curl -s {BASE_URL}/api/codex/scrape -H 'Content-Type: application/json' \\
     -d '{{"url": "$ARGUMENTS", "wait": true, "crawl_depth": 2}}'
   ```
5. Summarise the `completed_files` and every `failed_files` entry with its error.
"""


def build_claude_skill() -> str:
    return render_skill(AGENTS_BY_ID["claude"], BASE_URL)


def build_dsh_skill() -> str:
    return render_skill(AGENTS_BY_ID["dsh"], BASE_URL)


def build_gemini_settings() -> str:
    return json.dumps({
        "mcpServers": {"auto-get-py": mcp_stdio_config()},
    }, indent=2) + "\n"


def build_zed_settings() -> str:
    return json.dumps({
        "context_servers": {
            "auto-get-py": {
                "command": {"path": "python", "args": ["mcp_server.py"]},
                "settings": {"AUTO_GET_BASE_URL": BASE_URL},
            }
        }
    }, indent=2) + "\n"


def build_aider_conf() -> str:
    # YAML, so `#` comments rather than the markdown header.
    return f"""{HASH_HEADER}# Aider configuration for {PROJECT_NAME}
read:
  - CONVENTIONS.md
  - AGENTS.md
"""


def build_vscode_mcp() -> str:
    return json.dumps({
        "servers": {
            "auto-get-py": {
                "type": "stdio",
                "command": "python",
                "args": ["mcp_server.py"],
                "env": {"AUTO_GET_BASE_URL": BASE_URL},
            }
        }
    }, indent=2) + "\n"


def build_reference_doc(agent_id: str) -> str:
    return render_agent_doc(AGENTS_BY_ID[agent_id], BASE_URL)


def build_manifest_json() -> str:
    return json.dumps(build_manifest(BASE_URL), indent=2, ensure_ascii=False) + "\n"


# ── Path → content mapping ──────────────────────────────────────────────────
#
# Keys are repository-relative paths. Each producer is called with the agent id
# so per-agent files can specialise.

SPECIAL_FILES = {
    "AGENTS.md": lambda _id: build_agents_md(),
    "CLAUDE.md": lambda _id: build_claude_md(),
    "GEMINI.md": lambda _id: build_gemini_md(),
    "CONVENTIONS.md": lambda _id: build_agents_md(),
    ".rules": lambda _id: build_rules_markdown("zed", "/api/zed"),
    ".mcp.json": lambda _id: json.dumps(mcp_servers_json(), indent=2) + "\n",
    ".cursor/mcp.json": lambda _id: json.dumps(mcp_servers_json(), indent=2) + "\n",
    ".roo/mcp.json": lambda _id: json.dumps(mcp_servers_json(), indent=2) + "\n",
    ".windsurf/mcp.json": lambda _id: json.dumps(mcp_servers_json(), indent=2) + "\n",
    ".dsh/mcp.json": lambda _id: build_dsh_mcp(),
    ".vscode/mcp.json": lambda _id: build_vscode_mcp(),
    ".cursor/rules/auto-get-py.mdc": lambda _id: build_cursor_rule(),
    ".opencode/agent/scraper.md": lambda _id: build_opencode_agent(),
    "opencode.json": lambda _id: build_opencode_json(),
    ".codex/config.toml": lambda _id: build_codex_config(),
    ".codex/README.md": lambda _id: build_codex_readme(),
    ".codex/prompts/scrape.md": lambda _id: build_codex_prompt(),
    ".claude/skills/auto-get-py/SKILL.md": lambda _id: build_claude_skill(),
    ".dsh/skills/auto-get-py/SKILL.md": lambda _id: build_dsh_skill(),
    ".gemini/settings.json": lambda _id: build_gemini_settings(),
    ".zed/settings.json": lambda _id: build_zed_settings(),
    ".aider.conf.yml": lambda _id: build_aider_conf(),
    ".github/copilot-instructions.md": lambda _id: build_rules_markdown(
        "copilot", "/api/copilot"),
    ".clinerules/auto-get-py.md": lambda _id: build_rules_markdown("cline", "/api/cline"),
    ".roo/rules/auto-get-py.md": lambda _id: build_rules_markdown("roo", "/api/roo"),
    ".windsurf/rules/auto-get-py.md": lambda _id: build_rules_markdown(
        "windsurf", "/api/windsurf"),
    ".continue/rules/auto-get-py.md": lambda _id: build_rules_markdown(
        "continue", "/api/continue"),
}


def deliverables() -> dict[str, str]:
    """Every generated file, as ``{relative_path: content}``."""
    files: dict[str, str] = {}

    for agent in AGENTS:
        for path in agent.config_files:
            producer = SPECIAL_FILES.get(path)
            if producer is not None:
                files[path] = producer(agent.id)
            elif path.startswith("docs/agents/"):
                files[path] = build_reference_doc(agent.id)
            elif path.endswith("SKILL.md"):
                files[path] = render_skill(agent, BASE_URL)
            else:
                files[path] = build_reference_doc(agent.id)

        # Per-agent reference doc for every agent, whether or not it lists one.
        files.setdefault(f"docs/agents/{agent.id}.md", build_reference_doc(agent.id))

    files["docs/agents/README.md"] = build_agents_index()
    files["docs/agent-manifest.json"] = build_manifest_json()
    files["docs/HERMES_SKILL.md"] = render_skill(AGENTS_BY_ID["hermes"], BASE_URL)
    return files


def build_agents_index() -> str:
    rows = "\n".join(
        f"| [{agent.name}]({agent.id}.md) | `{agent.primary_prefix}` | "
        f"{agent.install or '—'} |"
        for agent in AGENTS
    )
    return f"""{GENERATED_HEADER}# Agent integrations

{PROJECT_NAME} exposes one canonical HTTP API and mounts it under a URL alias
for every supported tool, so an agent can use the path it already expects.

| Agent | URL alias | Install |
|---|---|---|
{rows}

## The canonical API

{_quick_reference()}

## Regenerating

```bash
python scripts/generate_agent_docs.py
```

Everything in this directory is generated from `api/agent_registry.py` and
`api/agent_docs.py`.
"""


# ── Output validation ───────────────────────────────────────────────────────


class GeneratedFileError(ValueError):
    """A generated file would not be usable by the tool it targets."""


def validate(path: str, content: str) -> None:
    """Fail loudly if a generated file is malformed or machine-specific.

    Two bugs this catches that are otherwise invisible until a user tries the
    integration: a comment in the wrong syntax (an HTML comment inside TOML or
    YAML makes the file unparseable), and a hard-coded local checkout path that
    is wrong on every other machine.
    """
    if path.endswith(".json"):
        try:
            json.loads(content)
        except json.JSONDecodeError as exc:
            raise GeneratedFileError(f"{path} is not valid JSON: {exc}") from exc

    elif path.endswith(".toml"):
        if tomllib is None:
            return
        try:
            tomllib.loads(content)
        except Exception as exc:  # noqa: BLE001 - tomllib raises several types
            raise GeneratedFileError(f"{path} is not valid TOML: {exc}") from exc

    elif path.endswith((".yml", ".yaml")):
        if yaml is None:
            return
        try:
            yaml.safe_load(content)
        except Exception as exc:  # noqa: BLE001 - yaml raises several types
            raise GeneratedFileError(f"{path} is not valid YAML: {exc}") from exc

    # A committed file must not contain the author's checkout path.
    for needle in (str(ROOT), ROOT.as_posix()):
        if needle and needle in content:
            raise GeneratedFileError(
                f"{path} embeds the local checkout path ({needle}); "
                f"generated files must be portable")


def validate_all(files: dict[str, str]) -> None:
    problems: list[str] = []
    for path, content in sorted(files.items()):
        try:
            validate(path, content)
        except GeneratedFileError as exc:
            problems.append(str(exc))
    if problems:
        raise GeneratedFileError(
            "generated output failed validation:\n  - " + "\n  - ".join(problems))


# ── CLI ─────────────────────────────────────────────────────────────────────


def _write(path: Path, content: str, check: bool, stale: list[str]) -> None:
    relative = path.relative_to(ROOT).as_posix()
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    if check:
        stale.append(relative)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"{'updated' if existing is not None else 'created'}  {relative}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if any generated file is out of date")
    args = parser.parse_args()

    files = deliverables()

    try:
        validate_all(files)
    except GeneratedFileError as exc:
        print(str(exc), file=sys.stderr)
        print("\nRefusing to write invalid output.", file=sys.stderr)
        return 1

    stale: list[str] = []
    for relative, content in sorted(files.items()):
        _write(ROOT / relative, content, args.check, stale)

    if args.check:
        if stale:
            print("Out-of-date generated files:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("\nRun: python scripts/generate_agent_docs.py", file=sys.stderr)
            return 1
        print(f"All {len(files)} generated files are up to date.")
        return 0

    print(f"\n{len(files)} files generated for {len(AGENTS)} agents.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
